# Generated by Django 5.0.14 on 2026-02-24 23:50

from django.db import migrations


def create_profiles(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Profile = apps.get_model("accounts", "Profile")
    existing = set(
        Profile.objects.values_list("user_id", flat=True)
    )
    to_create = [
        Profile(user_id=uid)
        for uid in User.objects.values_list("id", flat=True)
        if uid not in existing
    ]
    if to_create:
        Profile.objects.bulk_create(to_create)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_create_profile'),
    ]

    operations = [
        migrations.RunPython(create_profiles, migrations.RunPython.noop),
    ]
