# Generated by Django 5.0.7 on 2026-04-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_backfill_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_completed_onboarding',
            field=models.BooleanField(default=False),
        ),
    ]
