# Generated by Django 5.0.7 on 2026-04-04 16:18

from django.db import migrations


def set_existing_users_onboarded(apps, schema_editor):
    Profile = apps.get_model("accounts", "Profile")
    Profile.objects.all().update(has_completed_onboarding=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_has_completed_onboarding'),
    ]

    operations = [
        migrations.RunPython(
            set_existing_users_onboarded,
            migrations.RunPython.noop,
        ),
    ]
