# Generated by Django 5.2.4 on 2025-07-11 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0016_remove_goal_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('object_id', models.PositiveIntegerField()),
                ('entity_title', models.CharField(blank=True, max_length=255, null=True)),
                ('is_board_item', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mode')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
