# Generated by Django 5.0.7 on 2025-10-30 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0022_alter_mode_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pin',
            options={},
        ),
        migrations.AddField(
            model_name='pin',
            name='file_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pin',
            name='kind',
            field=models.CharField(choices=[('image', 'image'), ('link', 'link'), ('video', 'video'), ('file', 'file')], default='image', max_length=16),
        ),
        migrations.AddField(
            model_name='pin',
            name='mime_type',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='pin',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='pin',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='pin',
            name='entity_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pin',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='pins/'),
        ),
        migrations.AlterField(
            model_name='pin',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='core.mode'),
        ),
        migrations.AlterField(
            model_name='pin',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pin',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='pins/thumbs/'),
        ),
        migrations.AddIndex(
            model_name='pin',
            index=models.Index(fields=['kind'], name='boards_pin_kind_dee55d_idx'),
        ),
        migrations.AddIndex(
            model_name='pin',
            index=models.Index(fields=['created_at'], name='boards_pin_created_42885c_idx'),
        ),
    ]
