# Generated by Django 5.0.14 on 2025-12-14 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_pin_user'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0024_goal_user_milestone_user_mode_user_project_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='pin',
            index=models.Index(fields=['user', 'created_at'], name='boards_pin_user_id_87c973_idx'),
        ),
        migrations.AddIndex(
            model_name='pin',
            index=models.Index(fields=['user', 'kind'], name='boards_pin_user_id_d5038a_idx'),
        ),
        migrations.AddIndex(
            model_name='pin',
            index=models.Index(fields=['mode', 'created_at'], name='boards_pin_mode_id_76d2a2_idx'),
        ),
    ]
