# Generated by Django 5.2.4 on 2025-07-17 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0016_remove_goal_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('milestone', 'Milestone'), ('project', 'Project')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('data', models.JSONField()),
                ('is_public', models.BooleanField(default=False)),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mode')),
            ],
        ),
    ]
