# Generated by Django 5.0.14 on 2025-12-14 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_goal_user_milestone_user_mode_user_project_user_and_more'),
        ('templates', '0002_template_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='template',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='core.mode'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['user', 'created_at'], name='templates_t_user_id_4914d7_idx'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['user', 'mode', 'created_at'], name='templates_t_user_id_f7a02e_idx'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['type'], name='templates_t_type_434b8f_idx'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['is_public'], name='templates_t_is_publ_8f6905_idx'),
        ),
    ]
