# Generated by Django 5.0.7 on 2025-10-23 20:16

import comments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_remove_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentattachment',
            name='mime',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='commentattachment',
            name='original_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='commentattachment',
            name='file',
            field=models.FileField(upload_to=comments.models.attachment_upload_to),
        ),
    ]
