# Generated by Django 5.0.14 on 2025-12-14 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_comment_user_commentattachment_user'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0024_goal_user_milestone_user_mode_user_project_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.mode'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user', 'created_at'], name='comments_co_user_id_e44996_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user', 'mode', 'created_at'], name='comments_co_user_id_4c1121_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['content_type', 'object_id'], name='comments_co_content_cff8bd_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['is_deleted'], name='comments_co_is_dele_370027_idx'),
        ),
        migrations.AddIndex(
            model_name='commentattachment',
            index=models.Index(fields=['user', 'uploaded_at'], name='comments_co_user_id_644f5d_idx'),
        ),
        migrations.AddIndex(
            model_name='commentattachment',
            index=models.Index(fields=['comment', 'uploaded_at'], name='comments_co_comment_899e5d_idx'),
        ),
    ]
