# Generated by Django 5.2.4 on 2025-08-11 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_goal_is_archived'),
        ('timers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='timeentry',
            name='timers_time_user_id_6c6cd9_idx',
        ),
        migrations.RemoveIndex(
            model_name='timeentry',
            name='timers_time_user_id_f307db_idx',
        ),
        migrations.RemoveIndex(
            model_name='timeentry',
            name='timers_time_user_id_bbeda6_idx',
        ),
        migrations.RemoveIndex(
            model_name='timeentry',
            name='timers_time_user_id_0f8db2_idx',
        ),
        migrations.AlterField(
            model_name='activetimer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_timers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['started_at'], name='timers_time_started_d0734f_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['mode', 'started_at'], name='timers_time_mode_id_9e7149_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['task', 'started_at'], name='timers_time_task_id_a634d5_idx'),
        ),
    ]
