# Generated by Django 5.0.7 on 2025-09-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timers', '0002_remove_timeentry_timers_time_user_id_6c6cd9_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activetimer',
            name='planned_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activetimer',
            name='session_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='planned_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='session_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
