# Generated by Django 5.0.14 on 2025-11-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timers', '0003_activetimer_planned_seconds_activetimer_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='goal_title_snapshot',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='milestone_title_snapshot',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='mode_title_snapshot',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='project_title_snapshot',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='task_title_snapshot',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
