# Generated by Django 5.0.14 on 2025-12-09 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_goal_archived_at_goal_is_archived_and_more'),
        ('timers', '0005_alter_activetimer_user_alter_timeentry_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activetimer',
            name='mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_timers', to='core.mode'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='core.mode'),
        ),
    ]
