# Generated by Django 5.0.14 on 2025-12-14 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_goal_user_milestone_user_mode_user_project_user_and_more'),
        ('timers', '0006_alter_activetimer_mode_alter_timeentry_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='timeentry',
            name='timers_time_started_d0734f_idx',
        ),
        migrations.RemoveIndex(
            model_name='timeentry',
            name='timers_time_mode_id_9e7149_idx',
        ),
        migrations.RemoveIndex(
            model_name='timeentry',
            name='timers_time_task_id_a634d5_idx',
        ),
        migrations.AlterField(
            model_name='activetimer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_timers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='activetimer',
            index=models.Index(fields=['user', 'started_at'], name='timers_acti_user_id_72bcdc_idx'),
        ),
        migrations.AddIndex(
            model_name='activetimer',
            index=models.Index(fields=['user', 'ends_at'], name='timers_acti_user_id_60d71b_idx'),
        ),
        migrations.AddIndex(
            model_name='activetimer',
            index=models.Index(fields=['user', 'session_id'], name='timers_acti_user_id_0ed163_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['user', 'started_at'], name='timers_time_user_id_6c6cd9_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['user', 'mode', 'started_at'], name='timers_time_user_id_bbeda6_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['user', 'task', 'started_at'], name='timers_time_user_id_0f8db2_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['user', 'session_id'], name='timers_time_user_id_6e510e_idx'),
        ),
        migrations.AddConstraint(
            model_name='activetimer',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_active_timer_per_user'),
        ),
    ]
