# Generated by Django 5.0.7 on 2025-04-11 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_task_description_task_due_date_task_due_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mode',
            name='is_default',
        ),
    ]
