# Generated by Django 5.0.7 on 2025-04-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_task_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='mode',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
