# Generated by Django 5.0.7 on 2025-05-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_header_task_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
