# Generated by Django 5.0.7 on 2025-05-26 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_header_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.header'),
        ),
    ]
