# Generated by Django 5.0.7 on 2025-05-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_is_completed_task_is_done_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='header',
            old_name='is_done',
            new_name='is_completed',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='is_done',
            new_name='is_completed',
        ),
        migrations.AddField(
            model_name='goal',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
