# Generated by Django 5.0.7 on 2025-06-02 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_goal_parent_goal_due_date_goal_due_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='core.mode'),
        ),
        migrations.AddField(
            model_name='project',
            name='mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.mode'),
        ),
    ]
