# Generated by Django 5.0.7 on 2025-06-03 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_goal_mode_project_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='is_archived',
        ),
    ]
