# Generated by Django 5.2.5 on 2025-09-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_goal_is_archived'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='milestone',
            options={'ordering': ['position', 'id']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['position', 'id']},
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['mode', 'parent', 'position'], name='core_milest_mode_id_d44521_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['mode', 'project', 'parent', 'position'], name='core_milest_mode_id_2eff0b_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['mode', 'goal', 'parent', 'position'], name='core_milest_mode_id_8f3424_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['mode', 'milestone', 'position'], name='core_task_mode_id_e6829f_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['mode', 'project', 'milestone', 'position'], name='core_task_mode_id_3df3ff_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['mode', 'goal', 'project', 'milestone', 'position'], name='core_task_mode_id_4f7ee0_idx'),
        ),
    ]
