# Generated by Django 5.2.5 on 2025-09-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_milestone_options_alter_task_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='milestone',
            options={},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['position', 'id']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='milestone',
            name='core_milest_mode_id_d44521_idx',
        ),
        migrations.RemoveIndex(
            model_name='milestone',
            name='core_milest_mode_id_2eff0b_idx',
        ),
        migrations.RemoveIndex(
            model_name='milestone',
            name='core_milest_mode_id_8f3424_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='core_task_mode_id_e6829f_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='core_task_mode_id_3df3ff_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='core_task_mode_id_4f7ee0_idx',
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['mode', 'position'], name='core_projec_mode_id_dee9e3_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['goal', 'position'], name='core_projec_goal_id_f981ca_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['parent', 'position'], name='core_projec_parent__951c33_idx'),
        ),
    ]
