# Generated by Django 5.2.5 on 2025-09-03 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_goal_description_alter_project_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['position', 'id']},
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['mode', 'position'], name='core_goal_mode_id_c5d18d_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['is_completed'], name='core_goal_is_comp_ab2645_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['due_date'], name='core_goal_due_dat_80d975_idx'),
        ),
    ]
