# Generated by Django 5.0.7 on 2025-09-10 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_goal_options_goal_core_goal_mode_id_c5d18d_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='core.mode'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='core.mode'),
        ),
        migrations.AlterField(
            model_name='project',
            name='mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.mode'),
        ),
        migrations.AlterField(
            model_name='task',
            name='mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.mode'),
        ),
    ]
