# Generated by Django 5.0.7 on 2025-09-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_goal_mode_alter_milestone_mode_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mode',
            options={'ordering': ['position', 'id']},
        ),
        migrations.AddConstraint(
            model_name='milestone',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('parent__isnull', True), ('project__isnull', True), ('goal__isnull', True)), models.Q(('parent__isnull', False), ('project__isnull', True), ('goal__isnull', True)), models.Q(('parent__isnull', True), ('project__isnull', False), ('goal__isnull', True)), models.Q(('parent__isnull', True), ('project__isnull', True), ('goal__isnull', False)), _connector='OR'), name='milestone_at_most_one_parent_or_project_or_goal'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('parent__isnull', True), ('goal__isnull', True)), models.Q(('parent__isnull', False), ('goal__isnull', True)), models.Q(('parent__isnull', True), ('goal__isnull', False)), _connector='OR'), name='project_at_most_one_parent_or_goal'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('milestone__isnull', True), ('project__isnull', True), ('goal__isnull', True)), models.Q(('milestone__isnull', False), ('project__isnull', True), ('goal__isnull', True)), models.Q(('milestone__isnull', True), ('project__isnull', False), ('goal__isnull', True)), models.Q(('milestone__isnull', True), ('project__isnull', True), ('goal__isnull', False)), _connector='OR'), name='task_at_most_one_milestone_or_project_or_goal'),
        ),
    ]
