# Generated by Django 5.0.14 on 2025-11-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_mode_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='milestone',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['is_archived'], name='core_goal_is_arch_4f4381_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['is_archived'], name='core_milest_is_arch_215df7_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_archived'], name='core_projec_is_arch_cff167_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['is_archived'], name='core_task_is_arch_b10b56_idx'),
        ),
    ]
