# Generated by Django 5.0.14 on 2026-01-02 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_goal_user_milestone_user_mode_user_project_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='mode',
            constraint=models.UniqueConstraint(fields=('user', 'position'), name='unique_mode_position_per_user'),
        ),
    ]
