# Generated by Django 5.0.7 on 2026-03-16 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_fix_orphaned_children_of_archived_parents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('entity_type', models.CharField(choices=[('goal', 'Goal'), ('project', 'Project'), ('milestone', 'Milestone'), ('task', 'Task')], max_length=20)),
                ('entity_id', models.PositiveIntegerField()),
                ('position', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position'],
                'indexes': [models.Index(fields=['user', 'date'], name='core_dailyo_user_id_a21439_idx')],
                'unique_together': {('user', 'date', 'entity_type', 'entity_id')},
            },
        ),
    ]
